version: 2

updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"

  - package-ecosystem: "pip"
    directory: "/apps/frontend"
    schedule:
      interval: "weekly"

  - package-ecosystem: "pip"
    directory: "/apps/users-service"
    schedule:
      interval: "weekly"

  - package-ecosystem: "pip"
    directory: "/apps/orders-service"
    schedule:
      interval: "weekly"

  - package-ecosystem: "pip"
    directory: "/apps/payments-service"
    schedule:
      interval: "weekly"

  - package-ecosystem: "pip"
    directory: "/apps/inventory-service"
    schedule:
      interval: "weekly"
