apiVersion: apps/v1
kind: Deployment

metadata:
  name: {{ .Chart.Name }}

spec:
  replicas: {{ .Values.replicaCount }}

  selector:
    matchLabels:
      app: {{ .Chart.Name }}
      version: {{ .Values.version }}

  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
        version: {{ .Values.version }}

    spec:
      containers:
      - name: orders-service

        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"

        ports:
        - containerPort: 8000
      
      

        resources:
{{ toYaml .Values.resources | nindent 10 }}