{{- if .Values.canary.enabled }}

apiVersion: apps/v1
kind: Deployment

metadata:
  name: {{ .Chart.Name }}-v2

spec:
  replicas: {{ .Values.canary.replicaCount }}

  selector:
    matchLabels:
      app: {{ .Chart.Name }}
      version: v2

  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
        version: v2

    spec:
      containers:
        - name: {{ .Chart.Name }}

          image: "{{ .Values.image.repository }}:{{ .Values.canary.tag }}"

          ports:
            - containerPort: 8000

      {{- if .Values.env }}
          env:
      {{ toYaml .Values.env | nindent 6 }}
      {{- end }}    

          resources:
{{ toYaml .Values.resources | nindent 12 }}

{{- end }}