apiVersion: apps/v1
kind: Deployment
metadata:
  name: payments-service
  namespace: enterprise

spec:
  replicas: 2

  selector:
    matchLabels:
      app: payments-service

  template:
    metadata:
      labels:
        app: payments-service

    spec:
      containers:
        - name: payments

          image: 106551436513.dkr.ecr.us-east-1.amazonaws.com/payments-service:latest

          ports:
            - containerPort: 8000

          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"

            limits:
              cpu: "500m"
              memory: "512Mi"
