apiVersion: apps/v1
kind: Deployment

metadata:
  name: {{ .Chart.Name }}

spec:
  replicas: {{ .Values.replicaCount }}

  selector:
    matchLabels:
      app: {{ .Chart.Name }}
      version: {{ .Values.version }}

  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
        version: {{ .Values.version }}

    spec:
      containers:
      - name: inventory-service

        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"

        ports:
        - containerPort: 8000

      {{- if .Values.env }}
          env:
      {{ toYaml .Values.env | nindent 6 }}
      {{- end }}

        resources:
      {{ toYaml .Values.resources | nindent 10 }}