name: Build-Test

on:
  push:
    branches: [main]
    paths:
      - "apps/payments-service/**"

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Dependencies
        run: |
          pip install -r apps/payments-service/requirements.txt
          pip install pytest httpx

      - name: Run Tests
        working-directory: apps/payments-service
        run: |
          pwd
          ls -la
          python -m pytest -v

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build Docker Image
        run: |
          docker build \
            -t payments-service:${{ github.sha }} \
            ./apps/payments-service

      - name: Trivy Scan
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: payments-service:${{ github.sha }}
          severity: CRITICAL,HIGH
          ignore-unfixed: true
          exit-code: 0

      - name: Tag Image
        run: |
          docker tag payments-service:${{ github.sha }} \
          ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.us-east-1.amazonaws.com/payments-service:${{ github.sha }}

      - name: Push Image
        run: |
          docker push \
          ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.us-east-1.amazonaws.com/payments-service:${{ github.sha }}

      - name: Checkout GitOps Repo
        uses: actions/checkout@v4
        with:
          repository: yogeshwaran-98/enterprise-eks-gitops
          token: ${{ secrets.GITOPS_PAT }}
          path: gitops

      - name: Install yq
        run: |
          sudo wget -O /usr/bin/yq \
            https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64
          sudo chmod +x /usr/bin/yq

      - name: Update image tag
        run: |
          yq -i '.image.tag = "${{ github.sha }}"' \
          gitops/environments/production/payments-service-values.yaml

      - name: Commit GitOps Changes
        run: |
          cd gitops

          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

          git add .

          git diff --staged --quiet || \
          git commit -m "Update payments-service image to ${{ github.sha }}"

      - name: Push GitOps Changes
        run: |
          cd gitops
          git push
